version: '3'
services:
  db:
    image: mysql
    container_name: mysql
    volumes: 
      - mysql_vol:/var/lib/mysql　　
    environment:
      MYSQL_ROOT_PASSWORD: root   #環境変数
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
volumes: #トップレベルにもvolumesをmapで追加しないとダメ
  mysql_vol: